#!/usr/bin/env bash

if [[ "$@" =~ "serve" ]]; then
  PORT="-p 2022:2022"
fi

docker volume create fhir > /dev/null

docker run -it -e JAVA_OPTS='-Xmx2048m -Xms2048m' \
  $PORT \
  --mount source=fhir,target=/home/dev/.fhir \
  -v "$(pwd)":/home/dev/workspace shorthand-docker \
  "$@"
